# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Christoffer Magnedal
tagline:          'A Jekyll theme'
description:      ''
url:              https://magnedal.se
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'Christoffer Magnedal'
  url:            https://twitter.com/magnedal

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
sidebar_home_link:  true
github:
  repo:             https://github.com/ccholmgren/

google_analytics: 'UA-105774586-1'

include: _headers
